name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pandas=2.2.1
  - requests=2.31.0
  - pip=23.3.1
  - pip:
      - wandb==0.16.4
      - git+https://github.com/udacity/nd0821-c2-build-model-workflow-starter.git#egg=wandb-utils&subdirectory=components